package tag_parser

// Code generated by peg ./internal/tag_parser/tag.peg DO NOT EDIT.

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
)

const endSymbol rune = 1114112

/* The rule types inferred from the grammar are below. */
type pegRule uint8

const (
	ruleUnknown pegRule = iota
	ruleDocument
	ruleExtractor
	ruleTransformer
	ruleIdentifier
	ruleLetter
	ruleSkip
	ruleSkipLine
	ruleSpace
	ruleIndent
	ruleCarriageReturnLineFeed
	ruleCOMMA
	ruleEQUAL
	rulePegText
)

var rul3s = [...]string{
	"Unknown",
	"Document",
	"Extractor",
	"Transformer",
	"Identifier",
	"Letter",
	"Skip",
	"SkipLine",
	"Space",
	"Indent",
	"CarriageReturnLineFeed",
	"COMMA",
	"EQUAL",
	"PegText",
}

type token32 struct {
	pegRule
	begin, end uint32
}

func (t *token32) String() string {
	return fmt.Sprintf("\x1B[34m%v\x1B[m %v %v", rul3s[t.pegRule], t.begin, t.end)
}

type node32 struct {
	token32
	up, next *node32
}

func (node *node32) print(w io.Writer, pretty bool, buffer string) {
	var print func(node *node32, depth int)
	print = func(node *node32, depth int) {
		for node != nil {
			for c := 0; c < depth; c++ {
				fmt.Fprintf(w, " ")
			}
			rule := rul3s[node.pegRule]
			quote := strconv.Quote(string(([]rune(buffer)[node.begin:node.end])))
			if !pretty {
				fmt.Fprintf(w, "%v %v\n", rule, quote)
			} else {
				fmt.Fprintf(w, "\x1B[36m%v\x1B[m %v\n", rule, quote)
			}
			if node.up != nil {
				print(node.up, depth+1)
			}
			node = node.next
		}
	}
	print(node, 0)
}

func (node *node32) Print(w io.Writer, buffer string) {
	node.print(w, false, buffer)
}

func (node *node32) PrettyPrint(w io.Writer, buffer string) {
	node.print(w, true, buffer)
}

type tokens32 struct {
	tree []token32
}

func (t *tokens32) Trim(length uint32) {
	t.tree = t.tree[:length]
}

func (t *tokens32) Print() {
	for _, token := range t.tree {
		fmt.Println(token.String())
	}
}

func (t *tokens32) AST() *node32 {
	type element struct {
		node *node32
		down *element
	}
	tokens := t.Tokens()
	var stack *element
	for _, token := range tokens {
		if token.begin == token.end {
			continue
		}
		node := &node32{token32: token}
		for stack != nil && stack.node.begin >= token.begin && stack.node.end <= token.end {
			stack.node.next = node.up
			node.up = stack.node
			stack = stack.down
		}
		stack = &element{node: node, down: stack}
	}
	if stack != nil {
		return stack.node
	}
	return nil
}

func (t *tokens32) PrintSyntaxTree(buffer string) {
	t.AST().Print(os.Stdout, buffer)
}

func (t *tokens32) WriteSyntaxTree(w io.Writer, buffer string) {
	t.AST().Print(w, buffer)
}

func (t *tokens32) PrettyPrintSyntaxTree(buffer string) {
	t.AST().PrettyPrint(os.Stdout, buffer)
}

func (t *tokens32) Add(rule pegRule, begin, end, index uint32) {
	tree, i := t.tree, int(index)
	if i >= len(tree) {
		t.tree = append(tree, token32{pegRule: rule, begin: begin, end: end})
		return
	}
	tree[i] = token32{pegRule: rule, begin: begin, end: end}
}

func (t *tokens32) Tokens() []token32 {
	return t.tree
}

type TagParser struct {
	Buffer string
	buffer []rune
	rules  [14]func() bool
	parse  func(rule ...int) error
	reset  func()
	Pretty bool
	tokens32
}

func (p *TagParser) Parse(rule ...int) error {
	return p.parse(rule...)
}

func (p *TagParser) Reset() {
	p.reset()
}

type textPosition struct {
	line, symbol int
}

type textPositionMap map[int]textPosition

func translatePositions(buffer []rune, positions []int) textPositionMap {
	length, translations, j, line, symbol := len(positions), make(textPositionMap, len(positions)), 0, 1, 0
	sort.Ints(positions)

search:
	for i, c := range buffer {
		if c == '\n' {
			line, symbol = line+1, 0
		} else {
			symbol++
		}
		if i == positions[j] {
			translations[positions[j]] = textPosition{line, symbol}
			for j++; j < length; j++ {
				if i != positions[j] {
					continue search
				}
			}
			break search
		}
	}

	return translations
}

type parseError struct {
	p   *TagParser
	max token32
}

func (e *parseError) Error() string {
	tokens, err := []token32{e.max}, "\n"
	positions, p := make([]int, 2*len(tokens)), 0
	for _, token := range tokens {
		positions[p], p = int(token.begin), p+1
		positions[p], p = int(token.end), p+1
	}
	translations := translatePositions(e.p.buffer, positions)
	format := "parse error near %v (line %v symbol %v - line %v symbol %v):\n%v\n"
	if e.p.Pretty {
		format = "parse error near \x1B[34m%v\x1B[m (line %v symbol %v - line %v symbol %v):\n%v\n"
	}
	for _, token := range tokens {
		begin, end := int(token.begin), int(token.end)
		err += fmt.Sprintf(format,
			rul3s[token.pegRule],
			translations[begin].line, translations[begin].symbol,
			translations[end].line, translations[end].symbol,
			strconv.Quote(string(e.p.buffer[begin:end])))
	}

	return err
}

func (p *TagParser) PrintSyntaxTree() {
	if p.Pretty {
		p.tokens32.PrettyPrintSyntaxTree(p.Buffer)
	} else {
		p.tokens32.PrintSyntaxTree(p.Buffer)
	}
}

func (p *TagParser) WriteSyntaxTree(w io.Writer) {
	p.tokens32.WriteSyntaxTree(w, p.Buffer)
}

func (p *TagParser) SprintSyntaxTree() string {
	var bldr strings.Builder
	p.WriteSyntaxTree(&bldr)
	return bldr.String()
}

func Pretty(pretty bool) func(*TagParser) error {
	return func(p *TagParser) error {
		p.Pretty = pretty
		return nil
	}
}

func Size(size int) func(*TagParser) error {
	return func(p *TagParser) error {
		p.tokens32 = tokens32{tree: make([]token32, 0, size)}
		return nil
	}
}
func (p *TagParser) Init(options ...func(*TagParser) error) error {
	var (
		max                  token32
		position, tokenIndex uint32
		buffer               []rune
	)
	for _, option := range options {
		err := option(p)
		if err != nil {
			return err
		}
	}
	p.reset = func() {
		max = token32{}
		position, tokenIndex = 0, 0

		p.buffer = []rune(p.Buffer)
		if len(p.buffer) == 0 || p.buffer[len(p.buffer)-1] != endSymbol {
			p.buffer = append(p.buffer, endSymbol)
		}
		buffer = p.buffer
	}
	p.reset()

	_rules := p.rules
	tree := p.tokens32
	p.parse = func(rule ...int) error {
		r := 1
		if len(rule) > 0 {
			r = rule[0]
		}
		matches := p.rules[r]()
		p.tokens32 = tree
		if matches {
			p.Trim(tokenIndex)
			return nil
		}
		return &parseError{p, max}
	}

	add := func(rule pegRule, begin uint32) {
		tree.Add(rule, begin, position, tokenIndex)
		tokenIndex++
		if begin != position && position > max.end {
			max = token32{rule, begin, position}
		}
	}

	/*matchChar := func(c byte) bool {
		if buffer[position] == c {
			position++
			return true
		}
		return false
	}*/

	/*matchRange := func(lower byte, upper byte) bool {
		if c := buffer[position]; c >= lower && c <= upper {
			position++
			return true
		}
		return false
	}*/

	_rules = [...]func() bool{
		nil,
		/* 0 Document <- <(Extractor (';' Transformer)?)> */
		func() bool {
			position0, tokenIndex0 := position, tokenIndex
			{
				position1 := position
				if !_rules[ruleExtractor]() {
					goto l0
				}
				{
					position2, tokenIndex2 := position, tokenIndex
					if buffer[position] != rune(';') {
						goto l2
					}
					position++
					if !_rules[ruleTransformer]() {
						goto l2
					}
					goto l3
				l2:
					position, tokenIndex = position2, tokenIndex2
				}
			l3:
				add(ruleDocument, position1)
			}
			return true
		l0:
			position, tokenIndex = position0, tokenIndex0
			return false
		},
		/* 1 Extractor <- <(Identifier (COMMA Identifier EQUAL Identifier)*)> */
		func() bool {
			position4, tokenIndex4 := position, tokenIndex
			{
				position5 := position
				if !_rules[ruleIdentifier]() {
					goto l4
				}
			l6:
				{
					position7, tokenIndex7 := position, tokenIndex
					if !_rules[ruleCOMMA]() {
						goto l7
					}
					if !_rules[ruleIdentifier]() {
						goto l7
					}
					if !_rules[ruleEQUAL]() {
						goto l7
					}
					if !_rules[ruleIdentifier]() {
						goto l7
					}
					goto l6
				l7:
					position, tokenIndex = position7, tokenIndex7
				}
				add(ruleExtractor, position5)
			}
			return true
		l4:
			position, tokenIndex = position4, tokenIndex4
			return false
		},
		/* 2 Transformer <- <(Identifier (COMMA Identifier EQUAL Identifier)*)> */
		func() bool {
			position8, tokenIndex8 := position, tokenIndex
			{
				position9 := position
				if !_rules[ruleIdentifier]() {
					goto l8
				}
			l10:
				{
					position11, tokenIndex11 := position, tokenIndex
					if !_rules[ruleCOMMA]() {
						goto l11
					}
					if !_rules[ruleIdentifier]() {
						goto l11
					}
					if !_rules[ruleEQUAL]() {
						goto l11
					}
					if !_rules[ruleIdentifier]() {
						goto l11
					}
					goto l10
				l11:
					position, tokenIndex = position11, tokenIndex11
				}
				add(ruleTransformer, position9)
			}
			return true
		l8:
			position, tokenIndex = position8, tokenIndex8
			return false
		},
		/* 3 Identifier <- <(Skip <(Letter (Letter / '.')*)> Indent*)> */
		func() bool {
			position12, tokenIndex12 := position, tokenIndex
			{
				position13 := position
				if !_rules[ruleSkip]() {
					goto l12
				}
				{
					position14 := position
					if !_rules[ruleLetter]() {
						goto l12
					}
				l15:
					{
						position16, tokenIndex16 := position, tokenIndex
						{
							position17, tokenIndex17 := position, tokenIndex
							if !_rules[ruleLetter]() {
								goto l18
							}
							goto l17
						l18:
							position, tokenIndex = position17, tokenIndex17
							if buffer[position] != rune('.') {
								goto l16
							}
							position++
						}
					l17:
						goto l15
					l16:
						position, tokenIndex = position16, tokenIndex16
					}
					add(rulePegText, position14)
				}
			l19:
				{
					position20, tokenIndex20 := position, tokenIndex
					if !_rules[ruleIndent]() {
						goto l20
					}
					goto l19
				l20:
					position, tokenIndex = position20, tokenIndex20
				}
				add(ruleIdentifier, position13)
			}
			return true
		l12:
			position, tokenIndex = position12, tokenIndex12
			return false
		},
		/* 4 Letter <- <([A-Z] / [a-z] / '_')> */
		func() bool {
			position21, tokenIndex21 := position, tokenIndex
			{
				position22 := position
				{
					position23, tokenIndex23 := position, tokenIndex
					if c := buffer[position]; c < rune('A') || c > rune('Z') {
						goto l24
					}
					position++
					goto l23
				l24:
					position, tokenIndex = position23, tokenIndex23
					if c := buffer[position]; c < rune('a') || c > rune('z') {
						goto l25
					}
					position++
					goto l23
				l25:
					position, tokenIndex = position23, tokenIndex23
					if buffer[position] != rune('_') {
						goto l21
					}
					position++
				}
			l23:
				add(ruleLetter, position22)
			}
			return true
		l21:
			position, tokenIndex = position21, tokenIndex21
			return false
		},
		/* 5 Skip <- <Space*> */
		func() bool {
			{
				position27 := position
			l28:
				{
					position29, tokenIndex29 := position, tokenIndex
					if !_rules[ruleSpace]() {
						goto l29
					}
					goto l28
				l29:
					position, tokenIndex = position29, tokenIndex29
				}
				add(ruleSkip, position27)
			}
			return true
		},
		/* 6 SkipLine <- <(Indent* CarriageReturnLineFeed?)> */
		nil,
		/* 7 Space <- <(Indent / CarriageReturnLineFeed)+> */
		func() bool {
			position31, tokenIndex31 := position, tokenIndex
			{
				position32 := position
				{
					position35, tokenIndex35 := position, tokenIndex
					if !_rules[ruleIndent]() {
						goto l36
					}
					goto l35
				l36:
					position, tokenIndex = position35, tokenIndex35
					if !_rules[ruleCarriageReturnLineFeed]() {
						goto l31
					}
				}
			l35:
			l33:
				{
					position34, tokenIndex34 := position, tokenIndex
					{
						position37, tokenIndex37 := position, tokenIndex
						if !_rules[ruleIndent]() {
							goto l38
						}
						goto l37
					l38:
						position, tokenIndex = position37, tokenIndex37
						if !_rules[ruleCarriageReturnLineFeed]() {
							goto l34
						}
					}
				l37:
					goto l33
				l34:
					position, tokenIndex = position34, tokenIndex34
				}
				add(ruleSpace, position32)
			}
			return true
		l31:
			position, tokenIndex = position31, tokenIndex31
			return false
		},
		/* 8 Indent <- <(' ' / '\t' / '\v')> */
		func() bool {
			position39, tokenIndex39 := position, tokenIndex
			{
				position40 := position
				{
					position41, tokenIndex41 := position, tokenIndex
					if buffer[position] != rune(' ') {
						goto l42
					}
					position++
					goto l41
				l42:
					position, tokenIndex = position41, tokenIndex41
					if buffer[position] != rune('\t') {
						goto l43
					}
					position++
					goto l41
				l43:
					position, tokenIndex = position41, tokenIndex41
					if buffer[position] != rune('\v') {
						goto l39
					}
					position++
				}
			l41:
				add(ruleIndent, position40)
			}
			return true
		l39:
			position, tokenIndex = position39, tokenIndex39
			return false
		},
		/* 9 CarriageReturnLineFeed <- <('\r' / '\n')> */
		func() bool {
			position44, tokenIndex44 := position, tokenIndex
			{
				position45 := position
				{
					position46, tokenIndex46 := position, tokenIndex
					if buffer[position] != rune('\r') {
						goto l47
					}
					position++
					goto l46
				l47:
					position, tokenIndex = position46, tokenIndex46
					if buffer[position] != rune('\n') {
						goto l44
					}
					position++
				}
			l46:
				add(ruleCarriageReturnLineFeed, position45)
			}
			return true
		l44:
			position, tokenIndex = position44, tokenIndex44
			return false
		},
		/* 10 COMMA <- <(Skip ',' Indent*)> */
		func() bool {
			position48, tokenIndex48 := position, tokenIndex
			{
				position49 := position
				if !_rules[ruleSkip]() {
					goto l48
				}
				if buffer[position] != rune(',') {
					goto l48
				}
				position++
			l50:
				{
					position51, tokenIndex51 := position, tokenIndex
					if !_rules[ruleIndent]() {
						goto l51
					}
					goto l50
				l51:
					position, tokenIndex = position51, tokenIndex51
				}
				add(ruleCOMMA, position49)
			}
			return true
		l48:
			position, tokenIndex = position48, tokenIndex48
			return false
		},
		/* 11 EQUAL <- <(Skip '=' Indent*)> */
		func() bool {
			position52, tokenIndex52 := position, tokenIndex
			{
				position53 := position
				if !_rules[ruleSkip]() {
					goto l52
				}
				if buffer[position] != rune('=') {
					goto l52
				}
				position++
			l54:
				{
					position55, tokenIndex55 := position, tokenIndex
					if !_rules[ruleIndent]() {
						goto l55
					}
					goto l54
				l55:
					position, tokenIndex = position55, tokenIndex55
				}
				add(ruleEQUAL, position53)
			}
			return true
		l52:
			position, tokenIndex = position52, tokenIndex52
			return false
		},
		nil,
	}
	p.rules = _rules
	return nil
}
